# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b86d62ab05e318f482acc28e3d079401"
name = "custom-app"
handle = "custom-app-590"
application_url = "https://jump-date-sessions-respected.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wixo-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://jump-date-sessions-respected.trycloudflare.com/auth/callback",
  "https://jump-date-sessions-respected.trycloudflare.com/auth/shopify/callback",
  "https://jump-date-sessions-respected.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
