# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "custom-app"
client_id = "0c8532727c8b7ab233d9299a60900ee0"
application_url = "https://assembled-herself-ict-templates.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, write_orders, read_orders, write_customers, read_customers"

[auth]
redirect_urls = [
  "https://assembled-herself-ict-templates.trycloudflare.com/auth/callback",
  "https://assembled-herself-ict-templates.trycloudflare.com/auth/shopify/callback",
  "https://assembled-herself-ict-templates.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wixo-checkout.myshopify.com"
